### ISSUE TITLE
Doesn't work with `.jpe extension

### ISSUE THREAD

**Issue by matthewwong525** [fleetingnotes/fleeting-notes-obsidian#119]
**Describe the bug**
When adding an attachment to a note and then syncing to Obsidian, I noticed that the images do not show up in Obsidian's file explorer. For some reason, the file extension is being truncated. The file in question is a jpg on my phone but in the source property in the note on my pc, it shows up as .jpe which is not a valid extension. When I change the extension to .jpeg it shows up in the explorer

**To Reproduce**
1. Add this to source: `https://yixcweyqwkqyvebpmdvr.supabase.co/storage/v1/object/public/attachments/c0378068-0eca-41d8-a058-665e255f6a66.jpe`
2. Try to sync with obsidian plugin
3. Attachment doesnt' sync

**Expected behavior**
- Attachment should sync with all common attachment types
- https://discord.com/channels/910294799188385885/1148630648408518689/1148630648408518689
- ![image](https://github.com/fleetingnotes/fleeting-notes-obsidian/assets/20890995/8b7b6e4e-278c-4f8e-9ace-f16a3aed56d6)

**Comment by gonzalovelasco** [comment]
When I was testing, I observed that the same image successfully synced to the designated folder. However, despite the successful sync, I couldn't locate the image within Obsidian. This issue seems specific to images with a '.jpe' extension. In contrast, I can see other files with '.jpeg' and '.png' extensions without any problems.

**Comment by matthewwong525** [comment]
Great find @gonzalovelasco . I'm going to close this ticket
